# Generated by Django 5.1.5 on 2025-06-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrarusuario',
            name='ano_nasc',
        ),
        migrations.RemoveField(
            model_name='cadastrarusuario',
            name='dia_nasc',
        ),
        migrations.RemoveField(
            model_name='cadastrarusuario',
            name='mes_nasc',
        ),
    ]
